### PR TITLE
Update editors

### PR DESCRIPTION
**Pull request by DRK3**

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
You'll also want to update CODEOWNERS as a part of this PR.

**Comment by DRK3** [comment]
> You'll also want to update CODEOWNERS as a part of this PR.

Done!

**Comment by DRK3** [comment]
@msporny @OR13 @csuwildcat Are there any other updates to the editors list I should make? During the last EDV editors' call we talked about making sure the list is up-to-date.

**Comment by msporny** [comment]
> @msporny @OR13 @csuwildcat Are there any other updates to the editors list I should make? During the last EDV Editors call we talked about making sure the list is up-to-date.

I think @csuwildcat noted that he doesn't plan to actively edit the EDV spec now that the Hubs work has been split out. Can you confirm/deny, @csuwildcat?

@OR13 do you plan on being an active editor on the EDV spec during the next year?

**Comment by OR13** [comment]
@msporny I don't plan on being an active editor of the spec, and hearby consent to being moved to contributor / author.

I am eager to re-engage when there are multiple implementations passing the interop tests.

**Comment by csuwildcat** [comment]
> > @msporny @OR13 @csuwildcat Are there any other updates to the editors list I should make? During the last EDV Editors call we talked about making sure the list is up-to-date.
> 
> I think @csuwildcat noted that he doesn't plan to actively edit the EDV spec now that the Hubs work has been split out. Can you confirm/deny, @csuwildcat?
> 
> @OR13 do you plan on being an active editor on the EDV spec during the next year?

No problem on my end, the Editor space should be occupied by someone who can be more active. Nevertheless, I will continue to attend calls and remain interested in figuring out the EDV/Hub interop story.

**Comment by DRK3** [comment]
@OR13 @csuwildcat Thanks for letting us know- I've gone ahead and removed you from the editors list. In the working group call today I briefly discussed with @msporny regarding who should go in the Authors section, since we don't currently have one in the spec (everyone? major contributors?). Since it's not yet 100% clear, I've created this issue to discuss: #61. Once I've got a clear idea of it, I can make that section and add @OR13 and others.

**Pull request merged**
