### PR TITLE
Re-add Use Cases document.

### PR DESCRIPTION
**Pull request by dmitrizagidulin**

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
Could we put this in a separate repo? edv-use-cases? The reason I'm suggesting that is because that's typically how most W3C docs are created/tracked/pushed forward/etc.

**Comment by dmitrizagidulin** [comment]
> Could we put this in a separate repo? edv-use-cases? The reason I'm suggesting that is because that's typically how most W3C docs are created/tracked/pushed forward/etc.

We already have 3 repos, though.. Like.. I'd be really reluctant to have 4.

**Comment by dmitrizagidulin** [comment]
N/m, good point. Closing this PR for the moment; will ask Orie to create another repo just for the use cases.

**Comment by dmitrizagidulin** [comment]
Update: https://github.com/decentralized-identity/edv-use-cases has been created, so we'll be moving the use cases doc there, shortly.

**Pull request closed without merging**
